### ISSUE TITLE
KeyError when set "type": "float" in node.json

### ISSUE THREAD

**Issue by tioma18** [info-beamer/package-sdk#1]
Check, please. I tried to add parameter (float type) in Reception screen package. and I got error: KeyError: u'float' at line 162 of hosted.py.

**Comment by dividuum** [comment]
I guess you'll have to include a newer version of `hosted.py` in your project. The current version handles float: https://github.com/info-beamer/package-sdk/blob/master/hosted.py#L88. Does that help?

**Comment by tioma18** [comment]
Yes, thanks
